version: '3.2'
services:

  customers:
    build: customers-service
    environment:
      - REDIS_HOST=customers_db
    links:
      - customers_db
  customers_db:
    image: redis

  products:
    build: products-service
    environment:
      - REDIS_HOST=products_db
    links:
      - products_db
  products_db:
    image: redis

  invoices:
    build: invoices-service
    environment:
      - REDIS_HOST=invoices_db
      - CUSTOMERS_API=http://customers:8080
      - PRODUCTS_API=http://products:8080
    links:
      - invoices_db
  invoices_db:
    image: redis

  api-gateway:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./api-gateway:/etc/nginx
    links:
      - customers
      - products
      - invoices

